version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-10.13
    steps:
      - checkout
      - run: echo "Start build"
      - run: yarn install
      - run: yarn build
  lint:
    docker:
      - image: circleci/node:chakracore-10.13
    steps:
      - checkout
      - run: echo "Start lint"
      - run: yarn install
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:chakracore-10.13
    steps:
      - checkout
      - run: echo "Start test"
      - run: yarn install
      - run: yarn test --single-run
  e2e:
    docker:
      - image: circleci/node:chakracore-10.13
    steps:
      - checkout
      - run: echo "Start e2e"
      - run: yarn install
      - run: yarn e2e
workflow:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
        requires:
          - build
      - test:
        requires:
          - build
      - e2e:
        requires:
          - build
